
// { status: 200,
//   statusText: 'OK',
//   headers:
//    { 'access-control-allow-credentials': 'true',
//      'access-control-allow-headers': 'Content-Type,Authorization,Region,Cookie',
//      'access-control-allow-methods': 'GET,POST,OPTIONS',
//      'content-type': 'application/json;charset=utf-8',
//      date: 'Sun, 25 Feb 2018 13:49:25 GMT',
//      'x-app-rate-limit': '20:1,100:120',
//      'x-app-rate-limit-count': '1:1,2:120',
//      'x-method-rate-limit': '500:10',
//      'x-method-rate-limit-count': '1:10',
//      'content-length': '29396',
//      connection: 'Close' },
//   config:
//    { adapter: [Function: httpAdapter],
//      transformRequest: { '0': [Function: transformRequest] },
//      transformResponse: { '0': [Function: transformResponse] },
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers:
//       { Accept: 'application/json, text/plain, */*',
//         'User-Agent': 'axios/0.18.0' },
//      method: 'get',
//      url: 'https://kr.api.riotgames.com/lol/match/v3/matches/3040204762?api_key=RGAPI-82e2a2d1-c92c-425b-b35f-60dc5f8e9a4c',
//      data: undefined },
//   request:
//    ClientRequest {
//      domain: null,
//      _events:
//       { socket: [Function],
//         abort: [Function],
//         aborted: [Function],
//         error: [Function],
//         timeout: [Function],
//         prefinish: [Function: requestOnPrefinish] },
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedConnection: false,
//      _removedContLen: false,
//      _removedTE: false,
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket:
//       TLSSocket {
//         _tlsOptions: [Object],
//         _secureEstablished: true,
//         _securePending: false,
//         _newSessionPending: false,
//         _controlReleased: true,
//         _SNICallback: null,
//         servername: null,
//         npnProtocol: undefined,
//         alpnProtocol: false,
//         authorized: true,
//         authorizationError: null,
//         encrypted: true,
//         _events: [Object],
//         _eventsCount: 9,
//         connecting: false,
//         _hadError: false,
//         _handle: null,
//         _parent: null,
//         _host: 'kr.api.riotgames.com',
//         _readableState: [Object],
//         readable: false,
//         domain: null,
//         _maxListeners: undefined,
//         _writableState: [Object],
//         writable: false,
//         allowHalfOpen: false,
//         _bytesDispatched: 216,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: undefined,
//         _server: null,
//         ssl: null,
//         _requestCert: true,
//         _rejectUnauthorized: true,
//         parser: null,
//         _httpMessage: [Circular],
//         read: [Function],
//         _consuming: true,
//         _idleNext: null,
//         _idlePrev: null,
//         _idleTimeout: -1,
//         [Symbol(asyncId)]: 9,
//         [Symbol(bytesRead)]: 29829 },
//      connection:
//       TLSSocket {
//         _tlsOptions: [Object],
//         _secureEstablished: true,
//         _securePending: false,
//         _newSessionPending: false,
//         _controlReleased: true,
//         _SNICallback: null,
//         servername: null,
//         npnProtocol: undefined,
//         alpnProtocol: false,
//         authorized: true,
//         authorizationError: null,
//         encrypted: true,
//         _events: [Object],
//         _eventsCount: 9,
//         connecting: false,
//         _hadError: false,
//         _handle: null,
//         _parent: null,
//         _host: 'kr.api.riotgames.com',
//         _readableState: [Object],
//         readable: false,
//         domain: null,
//         _maxListeners: undefined,
//         _writableState: [Object],
//         writable: false,
//         allowHalfOpen: false,
//         _bytesDispatched: 216,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: undefined,
//         _server: null,
//         ssl: null,
//         _requestCert: true,
//         _rejectUnauthorized: true,
//         parser: null,
//         _httpMessage: [Circular],
//         read: [Function],
//         _consuming: true,
//         _idleNext: null,
//         _idlePrev: null,
//         _idleTimeout: -1,
//         [Symbol(asyncId)]: 9,
//         [Symbol(bytesRead)]: 29829 },
//      _header: 'GET /lol/match/v3/matches/3040204762?api_key=RGAPI-82e2a2d1-c92c-425b-b35f-60dc5f8e9a4c HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: kr.api.riotgames.com\r\nConnection: close\r\n\r\n',
//      _onPendingData: [Function: noopPendingOutput],
//      agent:
//       Agent {
//         domain: null,
//         _events: [Object],
//         _eventsCount: 1,
//         _maxListeners: undefined,
//         defaultPort: 443,
//         protocol: 'https:',
//         options: [Object],
//         requests: {},
//         sockets: [Object],
//         freeSockets: {},
//         keepAliveMsecs: 1000,
//         keepAlive: false,
//         maxSockets: Infinity,
//         maxFreeSockets: 256,
//         maxCachedSessions: 100,
//         _sessionCache: [Object] },
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/lol/match/v3/matches/3040204762?api_key=RGAPI-82e2a2d1-c92c-425b-b35f-60dc5f8e9a4c',
//      _ended: true,
//      res:
//       IncomingMessage {
//         _readableState: [Object],
//         readable: false,
//         domain: null,
//         _events: [Object],
//         _eventsCount: 3,
//         _maxListeners: undefined,
//         socket: [Object],
//         connection: [Object],
//         httpVersionMajor: 1,
//         httpVersionMinor: 1,
//         httpVersion: '1.1',
//         complete: true,
//         headers: [Object],
//         rawHeaders: [Array],
//         trailers: {},
//         rawTrailers: [],
//         upgrade: false,
//         url: '',
//         method: null,
//         statusCode: 200,
//         statusMessage: 'OK',
//         client: [Object],
//         _consuming: true,
//         _dumped: false,
//         req: [Circular],
//         responseUrl: 'https://kr.api.riotgames.com/lol/match/v3/matches/3040204762?api_key=RGAPI-82e2a2d1-c92c-425b-b35f-60dc5f8e9a4c',
//         read: [Function] },
//      aborted: undefined,
//      timeoutCb: null,
//      upgradeOrConnect: false,
//      parser: null,
//      maxHeadersCount: null,
//      _redirectable:
//       Writable {
//         _writableState: [Object],
//         writable: true,
//         domain: null,
//         _events: [Object],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         _options: [Object],
//         _redirectCount: 0,
//         _requestBodyLength: 0,
//         _requestBodyBuffers: [],
//         _onNativeResponse: [Function],
//         _currentRequest: [Circular],
//         _currentUrl: 'https://kr.api.riotgames.com/lol/match/v3/matches/3040204762?api_key=RGAPI-82e2a2d1-c92c-425b-b35f-60dc5f8e9a4c' },
//      [Symbol(outHeadersKey)]: { accept: [Array], 'user-agent': [Array], host: [Array] } },
//   data:
//    { gameId: 3040204762,
//      platformId: 'KR',
//      gameCreation: 1512914578555,
//      gameDuration: 1216,
//      queueId: 420,
//      mapId: 11,
//      seasonId: 10,
//      gameVersion: '7.24.211.4973',
//      gameMode: 'CLASSIC',
//      gameType: 'MATCHED_GAME',
//      teams: [ [Object], [Object] ],
//      participants:
//       [ [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object] ],
//      participantIdentities:
//       [ [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object],
//         [Object] ] } }